name: Update IPTV Playlist

on:
  schedule:
    - cron: '0 * * * *'  # Запуск каждый час
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Ensure playlist.m3u exists
        run: touch playlist.m3u

      - name: Run update script
        run: python .github/update_playlist.py

      - name: Add changes to git
        run: git add -u

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git commit -m 'Update playlist' || echo "No changes to commit"
          git push || echo "Nothing to push"
